name = "nully0x"
description = "A notes storage for nully0x"
license = "MIT"
homepage = "https://github.com/evjrob/zola-folio"
# The minimum version of Zola required
min_version = "0.19.2"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "nully0x"
homepage = "notes.nully0x.xyz"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author = "Lia Bogoev"
homepage = "http://bogoli.github.io/-folio/"
repo = "https://github.com/bogoli/-folio"
